import "./globals.css";
import Navbar from "./components/navbar/navbar";

export const metadata = {
  title: "Lulu Prod",
  description: "Generated by Lucas",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="text-textColor">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
